name: Build

on:
  push:
    branches: 
      - main   
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'ni yuklab olish
        uses: actions/checkout@v4

      - name: Flutter o'rnatish
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'   # Dart 3.8+ bilan ishlaydi

      - name: Dependenciyalarni yuklash
        run: flutter pub get

      - name: Kodni analiz qilish
        run: flutter analyze

      - name: Testlarni ishlatish
        run: flutter test

      - name: APK build qilish
        run: flutter build apk --release

      - name: APK faylni saqlash (Artifacts bo'limida yuklab olish uchun)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
